### PR TITLE
Sunbreak support

### PR DESCRIPTION
**Pull request by Glazelf**
Sunbreak support
Refer to #31 for to-do list etc.

Spoiler warning for (unrevealed) Sunbreak content (obviously?)

Note: This PR only includes *monster* info, no quests are included.

### CODE REVIEW

**Comment by CrimsonNynja** [comment]
@Glazelf Left some general comments, discussion on the related git issue #31 
Thanks for the PR though, I know how long it can take to add these when a major update like this comes out

**Comment by CrimsonNynja** [comment]
@Glazelf just 1 conflict to resolve, then I'll merge it all in

**Comment by Glazelf** [comment]
@CrimsonNynja I resolved the merge conflict.

**Comment by Glazelf** [comment]
On PC I see a notification that seems to suggest that there are conflicts, but this branch seems to be up to date with origin/master when I try to merge.
image

**Comment by Glazelf** [comment]
I literally rebased master into this branch but it still says this branch can't be rebased. Lol.
Could you merge it yourself? It should be quite obvious what to do, it's probably just the commas on the MST2 image link lines giving conflicts, because descriptions got added on the line after.
If not you can give me write access and I'll merge it manually that way.

image

**Comment by CrimsonNynja** [comment]
So bizarre. Looked on the app as well and the merge button is green there but when I press it it doesnt work anyway :/

Happy to give you write access though to try and fix this

**Comment by CrimsonNynja** [comment]
@Glazelf Also just merged in your other PR, so hopefully getting this one up to date with that might fix it as well. But I've invited you as a proper collaborator now, so once you accept that you should have write access

**Comment by Glazelf** [comment]
I have tried everything I could think of, I'll just make a new PR.
#35

**Pull request closed without merging**
